### ISSUE TITLE
escaping for unquoted attribute value

### ISSUE THREAD

**Issue by clarkevans** [observablehq/htl#19] opened 2020-12-01 04:11 UTC
What a lovely concept and implementation, thank you for writing it. I believe there may be an escaping deficiency with unquoted attribute values. The [regex](https://github.com/observablehq/htl/blob/42c2104654d3e95e49e1c09f906c7c53a99c5bac/src/index.js#L125) for [STATE_BEFORE_ATTRIBUTE_VALUE](https://html.spec.whatwg.org/multipage/parsing.html#before-attribute-value-state) does not seem to include escaping required by [STATE_ATTRIBUTE_VALUE_UNQUOTED](https://html.spec.whatwg.org/multipage/parsing.html#attribute-value-(unquoted)-state), which it should since the given character is "re-consumed". Moreover, the [regex](https://github.com/observablehq/htl/blob/42c2104654d3e95e49e1c09f906c7c53a99c5bac/src/index.js#L129) for this latter rule does not seem to escape characters such as the equal sign (`=`) nor the quote (`"`). I'm also unsure about the boolean attribute logic. Consider `<button disabled=$(a)$(b)`.  What happens when `a` is `false`? When the attribute name and equality sign are stripped, what happens to the user-provided content from `b`?

**Comment by clarkevans** [comment] 2020-12-17 16:07
Within a [fork](https://github.com/clarkevans/HypertextLiteral.jl) of this project to meet Julia sensibilities, I decided to do two things to simplify this: (a) make it illegal to have two interpolations in unquoted strings, (b) promote unquoted strings to single quote.  This simplifies the translation and escape contexts.

**Comment by mbostock** [comment] 2021-01-09 21:40
The extra escaping isn’t necessary because that case is already handled by the HTML5 specification. This:

```js
html`<font color=${'="red"'}>`
```

Is equivalent to this:

```html
<font color=="red">
```

Which is equivalent to this:

```html
<font color="=&quot;red&quot;">
```

Hypertext Literal doesn’t need to perform the full escaping here; it only needs to produce output that will be interpreted correctly by an HTML5-compliant parser.

In the case of boolean attributes with a trailing interpolated value:

```js
html`<font color=${false}${"blue"}>`
```

This is not interpreted as a boolean attribute because this test fails because input is the empty string (i.e., boolean attributes are only allowed if the interpolated value is followed by a space or a greater than sign):

https://github.com/observablehq/htl/blob/3d2a783ac7033a16961689759daf156b6fbb694b/src/index.js#L109

Hence, both values are treated as unquoted attribute values and concatenated, equivalent to:

```html
<font color=falseblue>
```

I’ve added tests in 8a67c95 to verify the intended behavior. Thanks!

**Closed by mbostock** 2021-01-09 21:40 UTC
