### ISSUE TITLE
Interpolating the same (reference-equal) node >1 times renders only 1 node

### ISSUE THREAD

**Issue by lionel-rowe** [observablehq/htl#47] opened 2023-02-04 06:06 UTC
```js
const textNode = htl.html`x`
htl.html`${textNode}${textNode}` // renders `x` (expected `xx`)
htl.html`${[textNode, textNode]}` // renders `x` (expected `xx`)
```

This can be fixed by calling `Node#cloneNode(true)` on all interpolated DOM nodes or arrays of DOM nodes. Demo here: [HTL DOM node interpolation bug](https://observablehq.com/d/a56e4d1c697a45e7)

**Comment by mootari** [comment] 2023-02-04 14:02
htl.html never clones elements, so this is the expected behavior. If you want to pass an element multiple times you should clone it beforehand.

**Comment by lionel-rowe** [comment] 2023-02-05 14:39
> htl.html never clones elements, so this is the expected behavior.

It certainly wasn't for me, and I can't see it documented anywhere either?

If it helps, my use case was this:

```js
const visuallySelectableSpan = htl.html`<span aria-hidden="true">&nbsp;</span>`
const wrap = (el) => htl.html`${[visuallySelectableSpan, el, visuallySelectableSpan]}`
const visuallySelectableCheckBox = htl.html`<label>${wrap(htl.html`<input type="checkbox">`)}</label>`
```

Similar use cases that would currently fail include joining elements with a delimiter element in a way that's logically similar to `String#join`:

```js
const delim = htl.html`<span class="some-pretty-nonsense"></span>`
const prettyList = (strs) => strs.flatMap((str, i) => i ? [delim, str] : str)
htl.html`${prettyList(['one', 'two', 'three', 'four'])}`
```

I've added demos for both of those under the [Use cases](https://observablehq.com/d/a56e4d1c697a45e7#use-cases) section

**Comment by mootari** [comment] 2023-02-05 15:05
> It certainly wasn't for me, and I can't see it documented anywhere either?

That's the way the DOM works: if you append an element anywhere, it is removed from its original position. Refer to [the MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/Node/appendChild) for more details.

I think the main problem here is that you expect that Element instances can be used like template strings. You can make your code work with a few small tweaks so that it always returns a new instance:
```js
const visuallySelectableSpan = () => htl.html`<span aria-hidden="true">&nbsp;`
const wrap = (el) => htl.html.fragment`${[visuallySelectableSpan(), el, visuallySelectableSpan()]}`
const visuallySelectableCheckBox = htl.html`<label>${wrap(htl.html`<input type="checkbox">`)}`
```
and
```js
const delim = () => htl.html`<span class="some-pretty-nonsense">`
const prettyList = (strs) => strs.flatMap((str, i) => i ? [delim(), str] : str)
htl.html`${prettyList(['one', 'two', 'three', 'four'])}`
```
Note that I've removed the closing tags to demonstrate that they're optional, and that I'm calling .fragment to avoid creating another span.

**Comment by mbostock** [comment] 2023-02-05 17:21
This is the intended behavior.

**Closed as not planned by mbostock** 2023-02-05 17:21 UTC

**Comment by lionel-rowe** [comment] 2023-02-05 23:55
> That's the way the DOM works: if you append an element anywhere, it is removed from its original position. Refer to [the MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/Node/appendChild) for more details.
> 
> I think the main problem here is that you expect that Element instances can be used like template strings.

It's more that I expect this kind of thing to be handled by the library, but fair enough if that's out of scope. I've left a new PR with a README change to document the behavior.
